language: julia

julia: 1.0

jobs:
  include:
    - stage: test
      os: linux
      env: STAGE=test
      script:
        - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
        - julia --check-bounds=yes -e 'using Pkg;Pkg.update();
                   Pkg.clone(pwd(), "Turing");
                   Pkg.build("Turing");
                   Pkg.test("Turing"; coverage=true)'
    - stage: test
      if: branch = master
      os: osx
      env: STAGE=test
      script:
        - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
        - julia --check-bounds=yes -e 'using Pkg;Pkg.update();
                   Pkg.clone(pwd(), "Turing");
                   Pkg.build("Turing");
                   Pkg.test("Turing"; coverage=true)'         
    - stage: documentation
      if: branch = master
      env: STAGE=documentation
      script:
        - julia -e 'using Pkg; Pkg.add("Documenter"), Pkg.add("DocumenterMarkdown"), Pkg.add("DynamicHMC")'
        - julia -e 'using Pkg, Turing;
                    cd(joinpath(dirname(pathof(Turing)), ".."));
                    include(joinpath("docs", "make.jl"))'
after_success:
  - julia -e 'if ENV["STAGE"] == "test"
                using Pkg; cd(Pkg.dir("Turing")); Pkg.add("Coverage");
                using Coverage; Coveralls.submit(process_folder())
              end'
notifications:
    email: false
