group: deprecated-2017Q3
addons:
    apt:
        sources:
           - ubuntu-toolchain-r-test
        packages:
           - gcc-5
           - g++-5
language: julia
julia:
  - 0.6
os:
  - linux
  - osx
env:
  - GROUP=Test
matrix:
    fast_finish: true
    allow_failures:
       - env: GROUP=Test
         os: osx

notifications:
    email: false
script:
  - if [ "$(uname)" != "Darwin" ]; then ln -s `which gcc-5` gcc && export PATH=`pwd`:$PATH && echo $PATH; sudo apt-get install hdf5-tools; fi
  - gcc -v
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.update();
             Pkg.clone(pwd(), "Turing");
             Pkg.build("Turing");
             if ENV["GROUP"] == "Test"
                Pkg.test("Turing"; coverage=true)
             else
                println("Unknown test command.")
             end'
after_success:
  - julia -e 'if ENV["GROUP"] == "Test"
                cd(Pkg.dir("Turing")); Pkg.add("Coverage");
                using Coverage; Coveralls.submit(process_folder())
              end'
notifications:
    email: false
